openapi: 3.0.0
info:
  version: '0.1'
  title: RESTful Endeavour Pattern
  description: ''
  
tags:
  - name: Bank Transfers - Endeavours 
    description: Create new bank transfers
paths:
  /helloworld/hi:
    get:
      description: "Test"
      tags:
        -  Hello, World
      responses:
        '200':
          description: OK   
          
  /my/bank-transfers/endeavours:
    post:
      tags:
        -  Bank Transfers - Endeavours       
      description: "Test"
      responses:
        '201':
          description: Created
    get:
      tags:
        -  Bank Transfers - Endeavours       
      description: "Test"
      responses:
        '200':
          description: OK        
    
  /my/bank-transfers/endeavours/{endeavour-id}:
    get:
      tags:
        -  Bank Transfers - Endeavours       
      parameters: 
        - in: path
          name: endeavour-id
          description: The User Id to access
          required: true
          schema:
            type: string 
      description: "Test"
      responses:
        '200':
          description: OK        
        '410':
          description: Gone - this has been deleted
    put:  
      tags:
        -  Bank Transfers - Endeavours       
      parameters: 
        - in: path
          name: endeavour-id
          description: The User Id to access
          required: true
          schema:
            type: string     
      description: "Test"
      responses:
        '202':
          description: Accepted       
    patch:  
      tags:
        -  Bank Transfers - Endeavours       
      parameters: 
        - in: path
          name: endeavour-id
          description: The User Id to access
          required: true
          schema:
            type: string     
      description: "Test"
      responses:
        '202':
          description: Accepted                 
    delete: 
      tags:
        -  Bank Transfers - Endeavours       
      parameters: 
        - in: path
          name: endeavour-id
          description: The User Id to access
          required: true
          schema:
            type: string     
      description: "Test"
      responses:
        '202':
          description: Accepted Delete Request        

  /my/bank-transfers/endeavours/{endeavour-id}/versions:
    get:     
      tags:
        -  Bank Transfers - Endeavours       
      parameters: 
        - in: path
          name: endeavour-id
          description: The User Id to access
          required: true
          schema:
            type: string    
      description: "Test"
      responses:
        '200':
          description: Ok  
          
  /my/bank-transfers/endeavours/{endeavour-id}/versions/{endeavour-version-id}:
    get:     
      tags:
        -  Bank Transfers - Endeavours       
      parameters: 
        - in: path
          name: endeavour-id
          description: The User Id to access
          required: true
          schema:
            type: string    
        - in: path
          name: endeavour-version-id
          description: The version Id of the latest endeavour response that the client has received. Launch will fail if this is not the latest version - i.e. you can only try to launch with the correct latest version.
          required: true
          schema:
            type: string               
      description: "Test"
      responses:
        '200':
          description: Ok     
  /my/bank-transfers/endeavours/{endeavour-id}/versions/{endeavour-version-id}/launch:
    put: 
      tags:
        -  Bank Transfers - Endeavours       
      parameters: 
        - in: path
          name: endeavour-id
          description: The User Id to access
          required: true
          schema:
            type: string    
        - in: path
          name: endeavour-version-id
          description: The version Id of the latest endeavour response that the client has received. Launch will fail if this is not the latest version - i.e. you can only try to launch with the correct latest version.
          required: true
          schema:
            type: string               
      description: "Test"
      responses:
        '202':
          description: Accepted     
        '410':
          description: Gone - this has been deleted          
        '422':
          description: Unprocessable - likely that the version id is not the latest version of this endeavour.

    
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/RossBugginsNHS/RESTfulEndeavour/0.1